In [ ]:
import pandas as pd
df1 = pd.read_csv(r'/content/Project/NJ.csv')
print(df1)
df1.size

FileNotFoundError: [Errno 2] No such file or directory: '/content/Project/NJ.csv'

In [ ]:
df2 = pd.read_csv(r'/content/Project/SF.csv')
print(df2)

list(df2.columns)

In [ ]:
df3 = pd.read_csv(r'/content/Project/NJ.csv')
print(df3)

list(df3.columns)

In [ ]:
df4 = pd.read_csv(r'/content/Project/SJ.csv')
print(df4)

list(df4.columns)

In [ ]:
df5 = pd.read_csv(r'/content/Project/NY.csv')
print(df5)

list(df5.columns)

In [ ]:
result = pd.concat([df1, df2, df3, df4, df5], ignore_index=True)
print(result)

      Unnamed: 0                                          Job Title  \
0              0                    NetSuite Data Analytics Manager
1              1                          Data Scientist, Analytics
2              2                                Data Analytics Lead
3              3                                     Data Analytics
4              4                           Data Analytics Developer
...          ...                                                ...
5895          95  Solix Data Architect____ Bloomfield IL(Onsite)...
5896          96                     Network Configuration Engineer
5897          97                Equity Stockloan PM / BA Consultant
5898          98               Senior Software Engineer (Front End)
5899          99  Generative AI Architect-----Houston, TX (HYBRI...

                                     Company Name  \
0                                  Anderson Frank
1     Meta Platforms, Inc. (f/k/a Facebook, Inc.)
2                           InfiCare Technologies
3                                       Syeta Inc
4                Phoenix Technology Partners, LLC
...                                           ...
5895                                 Sysmind, LLC
5896                        SOHO Square Solutions
5897                                        EDPSI
5898                      The Walt Disney Company
5899                            E-Solutions, Inc.

                                        Job Description              Location  \
0     Position:NetSuite Data Analyst / Data Analytic...  Jersey City, NJ, USA
1     Meta Platforms, Inc. (f/k/a Facebook, Inc.) ha...  Jersey City, NJ, USA
2     Position: Data Analytics Lead  Location: NYC, ...  Jersey City, NJ, USA
3     Role: Data Analytics Location: New York, NY, U...  Jersey City, NJ, USA
4     Position Summary: The Data Analytics Developer...  Jersey City, NJ, USA
...                                                 ...                   ...
5895  Role-Solix Data Architect  Location: Bloomfiel...     New York, NY, USA
5896  Description: Experience with version control s...     New York, NY, USA
5897  Job Title: Project Manager 3 - 6 YOE - consult...     New York, NY, USA
5898  Disney Entertainment & ESPN Technology  On any...     New York, NY, USA
5899  Position :Generative AI Practice Leader Locati...     New York, NY, USA

            Employment Type         Posted Date  \
0                 Full-time   Posted 4 days ago
1                 Full-time   Posted 3 days ago
2               Third Party  Posted 10 days ago
3     Third Party, Contract  Posted 11 days ago
4                 Full-time   Posted 5 days ago
...                     ...                 ...
5895  Third Party, Contract   Posted 2 days ago
5896  Contract, Third Party   Posted 6 days ago
5897               Contract  Posted 12 days ago
5898              Full-time  Posted 23 days ago
5899  Third Party, Contract  Posted 25 days ago

                                           Company Link
0     https://www.dice.com/company/103716af?companyn...
1     https://www.dice.com/company/80180242?companyn...
2     https://www.dice.com/company/10113809?companyn...
3     https://www.dice.com/company/91121733?companyn...
4     https://www.dice.com/company/10195970?companyn...
...                                                 ...
5895  https://www.dice.com/company/10114932?companyn...
5896  https://www.dice.com/company/90806069?companyn...
5897  https://www.dice.com/company/edpsi?companyname...
5898  https://www.dice.com/company/waltdfa?companyna...
5899  https://www.dice.com/company/10211255?companyn...

[5900 rows x 8 columns]

In [ ]:
result.columns = result.columns.str.replace('Unnamed: 0','Index')

In [ ]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5900 entries, 0 to 5899
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            5900 non-null   int64
 1   Job Title        5900 non-null   object
 2   Company Name     5900 non-null   object
 3   Job Description  5900 non-null   object
 4   Location         5900 non-null   object
 5   Employment Type  5900 non-null   object
 6   Posted Date      5900 non-null   object
 7   Company Link     5900 non-null   object
dtypes: int64(1), object(7)
memory usage: 368.9+ KB

In [ ]:
result.isna().sum()

Index              0
Job Title          0
Company Name       0
Job Description    0
Location           0
Employment Type    0
Posted Date        0
Company Link       0
dtype: int64

In [ ]:
data_roles = result[result['Job Title'].apply(lambda title: 'data' in title.lower() and 'analytics' in title.lower())]
print(data_roles)

      Index                                          Job Title  \
0         0                    NetSuite Data Analytics Manager
1         1                          Data Scientist, Analytics
2         2                                Data Analytics Lead
3         3                                     Data Analytics
4         4                           Data Analytics Developer
...     ...                                                ...
5743     43                           Data Analytics Developer
5794     94                    NetSuite Data Analytics Manager
5832     32                                Data Analytics Lead
5846     46  CDO/CDAO (Chief Data officer) - Data and Analy...
5878     78    Manager, Data Science, Analytics - Go-to-Market

                                     Company Name  \
0                                  Anderson Frank
1     Meta Platforms, Inc. (f/k/a Facebook, Inc.)
2                           InfiCare Technologies
3                                       Syeta Inc
4                Phoenix Technology Partners, LLC
...                                           ...
5743             Phoenix Technology Partners, LLC
5794                               Anderson Frank
5832                        InfiCare Technologies
5846                                       ApTask
5878                                     DoorDash

                                        Job Description              Location  \
0     Position:NetSuite Data Analyst / Data Analytic...  Jersey City, NJ, USA
1     Meta Platforms, Inc. (f/k/a Facebook, Inc.) ha...  Jersey City, NJ, USA
2     Position: Data Analytics Lead  Location: NYC, ...  Jersey City, NJ, USA
3     Role: Data Analytics Location: New York, NY, U...  Jersey City, NJ, USA
4     Position Summary: The Data Analytics Developer...  Jersey City, NJ, USA
...                                                 ...                   ...
5743  Position Summary: The Data Analytics Developer...     New York, NY, USA
5794  Position:NetSuite Data Analyst / Data Analytic...     New York, NY, USA
5832  Position: Data Analytics Lead  Location: NYC, ...     New York, NY, USA
5846  Desired Skills Data Concepts & Data Modelling ...     New York, NY, USA
5878  About the Team The Merchant Core Analytics tea...     New York, NY, USA

            Employment Type         Posted Date  \
0                 Full-time   Posted 4 days ago
1                 Full-time   Posted 3 days ago
2               Third Party  Posted 10 days ago
3     Third Party, Contract  Posted 11 days ago
4                 Full-time   Posted 5 days ago
...                     ...                 ...
5743              Full-time   Posted 5 days ago
5794              Full-time   Posted 4 days ago
5832            Third Party  Posted 10 days ago
5846              Full-time  Posted 25 days ago
5878              Full-time  Posted 26 days ago

                                           Company Link
0     https://www.dice.com/company/103716af?companyn...
1     https://www.dice.com/company/80180242?companyn...
2     https://www.dice.com/company/10113809?companyn...
3     https://www.dice.com/company/91121733?companyn...
4     https://www.dice.com/company/10195970?companyn...
...                                                 ...
5743  https://www.dice.com/company/10195970?companyn...
5794  https://www.dice.com/company/103716af?companyn...
5832  https://www.dice.com/company/10113809?companyn...
5846  https://www.dice.com/company/10441603?companyn...
5878  https://www.dice.com/company/90917094?companyn...

[311 rows x 8 columns]

In [1]:
result["Employment Type"].value_counts.plot(kind=barh)

NameError: name 'result' is not defined

In [ ]:
distribution = result.groupby('Employment Type').size()
print(distribution)

Employment Type
Contract                                       1301
Contract, Third Party                           190
Full-time                                      4123
Full-time, Contract                              60
Full-time, Contract, Third Party                 10
Full-time, Part-time, Contract, Third Party      40
Full-time, Part-time, Third Party, Contract      18
Full-time, Third Party                           24
Full-time, Third Party, Contract                  5
Part-time                                        14
Third Party                                      18
Third Party, Contract                            97
dtype: int64

In [ ]:
from datetime import datetime, timedelta

result['Posted Date'] = pd.to_datetime(result['Posted Date'])

current_date = datetime.now()

date_ranges = [
    (current_date - timedelta(days=70), current_date - timedelta(days=61)),  # 61-70 days ago
    (current_date - timedelta(days=60), current_date - timedelta(days=51)),  # 51-60 days ago
    (current_date - timedelta(days=50), current_date - timedelta(days=41)),  # 41-50 days ago
    (current_date - timedelta(days=40), current_date - timedelta(days=31)),  # 31-40 days ago
    (current_date - timedelta(days=30), current_date - timedelta(days=21)),  # 21-30 days ago
    (current_date - timedelta(days=20), current_date - timedelta(days=11)),  # 11-20 days ago
    (current_date - timedelta(days=10), current_date),   # 0-10 days ago
]

labels = [
    '61-70 days ago',
    '51-60 days ago',
    '41-50 days ago',
    '31-40 days ago',
    '21-30 days ago',
    '11-20 days ago',
    '0-10 days ago',
]

result['Posted Date Category'] = pd.cut(result['Posted Date'], bins=[date_range[0] for date_range in date_ranges] + [current_date], labels=labels)

job_counts = result['Posted Date Category'].value_counts()
for category, count in job_counts.items():
    print(f'Number of jobs posted in the last {category}: {count}')

Number of jobs posted in the last 51-60 days ago: 1
Number of jobs posted in the last 0-10 days ago: 1
Number of jobs posted in the last 61-70 days ago: 0
Number of jobs posted in the last 41-50 days ago: 0
Number of jobs posted in the last 31-40 days ago: 0
Number of jobs posted in the last 21-30 days ago: 0
Number of jobs posted in the last 11-20 days ago: 0